name: gijilai_app
description: 기질아이 - 과학적 기질 분석 기반 맞춤형 육아 가이드
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  in_app_purchase: ^3.2.0
  firebase_core: ^3.13.0
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
